language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: hhvm
  allow_failures:
    - php: hhvm

before_install:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update

install:
  - composer install

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/php-cs-fixer fix --diff --dry-run -v
  - ./bin/console lint:yaml app/config
  - ./bin/console lint:twig app/Resources/views
  - ./bin/console lint:xliff app/Resources/translations
